### ISSUE TITLE
failed building on macos 10.7

### ISSUE THREAD

**Issue by davyzhang** [acg/lwpb#6]
ld: warning: ignoring file ../src/.libs/liblwpb.a, file was built for archive which is not the architecture being linked (i386)
ld: duplicate symbol _value in build/temp.macosx-10.6-intel-2.7/descriptor.o and build/temp.macosx-10.6-intel-2.7/decoder.o for architecture i386
collect2: ld returned 1 exit status
ld: duplicate symbol _value in build/temp.macosx-10.6-intel-2.7/descriptor.o and build/temp.macosx-10.6-intel-2.7/decoder.o for architecture x86_64
collect2: ld returned 1 exit status
lipo: can't open input file: /var/folders/r6/j1x0wz_s3wz507f660m6shmm0000gn/T//ccV3f4Ew.out (No such file or directory)
error: command 'gcc-4.2' failed with exit status 1
running clean
removing 'build/temp.macosx-10.6-intel-2.7' (and everything under it)

any hints? thanks a lot

**Comment by davyzhang** [comment]
from python setup.py build

**Comment by davyzhang** [comment]
build on centos 6 64bit
also get the arch error:

gcc -pthread -shared build/temp.linux-x86_64-2.7/decoder.o build/temp.linux-x86_64-2.7/descriptor.o build/temp.linux-x86_64-2.7/encoder.o build/temp.linux-x86_64-2.7/module.o build/temp.linux-x86_64-2.7/primitives.o -L../src/.libs -llwpb -o build/lib.linux-x86_64-2.7/lwpb/cext.so
/usr/bin/ld: ../src/.libs/liblwpb.a(liblwpb_la-decoder.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
../src/.libs/liblwpb.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by acg** [comment]
Looks like a cross compile gone bad. You're mixing 10.6 and 10.7, as well as i386 and x86_64. Did you switch machines but not make clean? Just a guess, I don't have access to a Mac at the moment. Let me know if you figure it out.

-Alan

**Comment by acg** [comment]
The second error on centos 64bit is probably legitimate though. What python version are you using there?

**Comment by davyzhang** [comment]
the second centos 64bit is 
uname -a
Linux dev218 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux

python version is 

Python 2.7.2 (default, Feb  7 2012, 00:04:24) 
[GCC 4.4.6 20110731 (Red Hat 4.4.6-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > exit()

**Comment by acg** [comment]
I just pushed a fix for the second issue (centos 64 bit build). Try your 64 bit compile again with:

```
make distclean && ./autogen.sh && ./configure && make
cd python
rm -rf build
python setup.py build
```

**Comment by davyzhang** [comment]
works like a charm~ thanks so much

**Comment by davyzhang** [comment]
on macos, I tried 
./configure CC="gcc -arch x86_64" CXX="g++ -arch x86_64"
and
export ARCHFLAGS='-arch x86_64'
python2.7 setup.py build --force

the arch problem seems gone, but the duiplicate symbol _value still there, I guess something being included twice ?

I'll let you know if I get any progress on this

ld: duplicate symbol _value in build/temp.macosx-10.6-x86_64-2.7/descriptor.o and build/temp.macosx-10.6-x86_64-2.7/decoder.o for architecture x86_64
collect2: ld returned 1 exit status
error: command 'gcc-4.2' failed with exit status 1

**Comment by acg** [comment]
Just pushed what may be a fix for your macos build issue, try your build again and let me know if it works now.

**Comment by davyzhang** [comment]
compiled done on macos 10.7, thanks so much for your efforts~!
